name: A workflow for my first GitHub Action
on: push
jobs:
  build:
    name: My first Hello World action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./actions
        with:
          MY_NAME: "Vaibhav"
